FROM python:3.11

# Set working directory
WORKDIR /usr/src/app

# Copy dependencies
COPY requirements.txt ./

# Install dependencies
RUN pip install --trusted-host pypi.python.org --no-cache-dir -r requirements.txt

# Copy application code
COPY . .