"""inst cookies app

Revision ID: 084d68bfed99
Revises: 3b75d8920cae
Create Date: 2024-11-30 15:53:19.996059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '084d68bfed99'
down_revision: Union[str, None] = '3b75d8920cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inst_app_id', sa.String(length=255), nullable=True),
    sa.Column('inst_app_secret', sa.String(length=255), nullable=True),
    sa.Column('webhook_callback_url', sa.String(length=255), nullable=True),
    sa.Column('webhook_verify_token', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('cookies',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('cookies_data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('instagram_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_accounts_id'), 'instagram_accounts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instagram_accounts_id'), table_name='instagram_accounts')
    op.drop_table('instagram_accounts')
    op.drop_table('cookies')
    op.drop_table('app')
    # ### end Alembic commands ###
