"""bot_url to bot_id

Revision ID: 11acf11a422b
Revises: 1dd5655d5196
Create Date: 2024-12-26 14:41:46.734388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11acf11a422b'
down_revision: Union[str, None] = '1dd5655d5196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instagram_users', sa.Column('bot_id', sa.String(), nullable=True))
    op.drop_column('instagram_users', 'bot_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instagram_users', sa.Column('bot_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('instagram_users', 'bot_id')
    # ### end Alembic commands ###
