"""remove external

Revision ID: 25b260ac3e32
Revises: 7febb99254df
Create Date: 2024-12-26 19:09:49.661270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25b260ac3e32'
down_revision: Union[str, None] = '7febb99254df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('external_service_app')
    op.add_column('telegram_users', sa.Column('bot_id', sa.String(), nullable=True))
    op.drop_column('telegram_users', 'bot_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('bot_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('telegram_users', 'bot_id')
    op.create_table('external_service_app',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('external_service_base_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='external_service_app_pkey')
    )
    # ### end Alembic commands ###
