"""lengthen to thousand

Revision ID: 2d2adf2121d7
Revises: 49efb6b55d12
Create Date: 2024-12-13 22:55:25.928524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d2adf2121d7'
down_revision: Union[str, None] = '49efb6b55d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instagram_app', 'embed_url',
               existing_type=sa.VARCHAR(length=800),
               type_=sa.String(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instagram_app', 'embed_url',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=800),
               existing_nullable=True)
    # ### end Alembic commands ###
