"""verifytokentable

Revision ID: 2d4b1e9fb85e
Revises: 2d2adf2121d7
Create Date: 2024-12-13 23:18:39.076769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d4b1e9fb85e'
down_revision: Union[str, None] = '2d2adf2121d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_verify_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verify_token', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instagram_verify_token')
    # ### end Alembic commands ###
