"""url to id whatsapp bot

Revision ID: 3fe1c8a896eb
Revises: 424d053c2c43
Create Date: 2024-12-27 09:02:01.276618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe1c8a896eb'
down_revision: Union[str, None] = '424d053c2c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_users', sa.Column('bot_id', sa.String(), nullable=True))
    op.drop_column('whatsapp_users', 'bot_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_users', sa.Column('bot_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('whatsapp_users', 'bot_id')
    # ### end Alembic commands ###
