"""externalservicebaseurl

Revision ID: 424051a80a6e
Revises: 98cd755e09db
Create Date: 2024-12-18 11:50:32.118073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '424051a80a6e'
down_revision: Union[str, None] = '98cd755e09db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instagram_verify_token')
    op.add_column('instagram_app', sa.Column('external_service_base_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instagram_app', 'external_service_base_url')
    op.create_table('instagram_verify_token',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('verify_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='instagram_verify_token_pkey'),
    sa.UniqueConstraint('id', name='instagram_verify_token_id_key')
    )
    # ### end Alembic commands ###
