"""authorized check remove wh

Revision ID: 43dfa17999fe
Revises: a380728e0271
Create Date: 2024-12-27 21:33:50.099737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43dfa17999fe'
down_revision: Union[str, None] = 'a380728e0271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_users', 'authorized')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_users', sa.Column('authorized', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
