"""quick fix tg

Revision ID: 49efb6b55d12
Revises: 9f75f1241cf2
Create Date: 2024-12-13 18:31:46.102039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49efb6b55d12'
down_revision: Union[str, None] = '9f75f1241cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('phone_code_hash', sa.String(), nullable=True))
    op.alter_column('telegram_users', 'session',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('telegram_users', 'app_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegram_users', 'app_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('telegram_users', 'session',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('telegram_users', 'phone_code_hash')
    # ### end Alembic commands ###
