"""remove cookies_model

Revision ID: 4d534b963a91
Revises: 8defd907c2c3
Create Date: 2024-12-01 17:44:37.617170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d534b963a91'
down_revision: Union[str, None] = '8defd907c2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cookies')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cookies',
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cookies_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('email', name='cookies_pkey')
    )
    # ### end Alembic commands ###
