"""embed_url

Revision ID: 5b6ad5dde436
Revises: f5e7b1931c8c
Create Date: 2024-12-01 19:03:46.905080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b6ad5dde436'
down_revision: Union[str, None] = 'f5e7b1931c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('embed_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app', 'embed_url')
    # ### end Alembic commands ###
