"""delete tgmessagelogs

Revision ID: 7b2ec3a9fb1b
Revises: 25b260ac3e32
Create Date: 2024-12-27 08:19:03.383676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b2ec3a9fb1b'
down_revision: Union[str, None] = '25b260ac3e32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_message_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('input_text', sa.String(), nullable=False),
    sa.Column('output_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_message_logs_id'), 'telegram_message_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_message_logs_id'), table_name='telegram_message_logs')
    op.drop_table('telegram_message_logs')
    # ### end Alembic commands ###
