"""return back phonecodehash

Revision ID: 7ee82f871c9a
Revises: 81fbc59b2a27
Create Date: 2024-12-18 13:48:59.841694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ee82f871c9a'
down_revision: Union[str, None] = '81fbc59b2a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('phone_code_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_users', 'phone_code_hash')
    # ### end Alembic commands ###
