"""add external service table2

Revision ID: 80292b1ae268
Revises: d3bae75eb4ea
Create Date: 2024-12-18 13:01:14.762131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80292b1ae268'
down_revision: Union[str, None] = 'd3bae75eb4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_service_app',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_service_base_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('external_service_app')
    # ### end Alembic commands ###
