"""add bot_url to tg

Revision ID: 81fbc59b2a27
Revises: 80292b1ae268
Create Date: 2024-12-18 13:46:24.399203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81fbc59b2a27'
down_revision: Union[str, None] = '80292b1ae268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('bot_url', sa.String(), nullable=True))
    op.drop_column('telegram_users', 'phone_code_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('phone_code_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('telegram_users', 'bot_url')
    # ### end Alembic commands ###
