"""fix

Revision ID: 8defd907c2c3
Revises: 084d68bfed99
Create Date: 2024-11-30 23:35:55.602516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8defd907c2c3'
down_revision: Union[str, None] = '084d68bfed99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app', 'inst_app_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'app', ['id'])
    op.create_unique_constraint(None, 'app', ['inst_app_id'])
    op.drop_constraint('instagram_accounts_app_id_fkey', 'instagram_accounts', type_='foreignkey')
    op.drop_column('instagram_accounts', 'app_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instagram_accounts', sa.Column('app_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('instagram_accounts_app_id_fkey', 'instagram_accounts', 'app', ['app_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'app', type_='unique')
    op.drop_constraint(None, 'app', type_='unique')
    op.alter_column('app', 'inst_app_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
