"""embed url str lengh

Revision ID: 9f75f1241cf2
Revises: 1afdeb459d61
Create Date: 2024-12-13 18:18:43.295391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f75f1241cf2'
down_revision: Union[str, None] = '1afdeb459d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instagram_app', 'inst_app_id',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('instagram_app', 'embed_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=800),
               existing_nullable=True)
    op.create_unique_constraint(None, 'instagram_app', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instagram_app', type_='unique')
    op.alter_column('instagram_app', 'embed_url',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('instagram_app', 'inst_app_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###
