"""add botid to whatsappuser

Revision ID: a380728e0271
Revises: 5ae6b83c1543
Create Date: 2024-12-27 15:29:20.422504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a380728e0271'
down_revision: Union[str, None] = '5ae6b83c1543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_users', sa.Column('bot_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'whatsapp_users', ['bot_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whatsapp_users', type_='unique')
    op.drop_column('whatsapp_users', 'bot_id')
    # ### end Alembic commands ###
