"""swaptablelog source message

Revision ID: c83bf078b1e2
Revises: 7b2ec3a9fb1b
Create Date: 2024-12-27 08:37:31.422836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c83bf078b1e2'
down_revision: Union[str, None] = '7b2ec3a9fb1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telegram_message_logs_id', table_name='telegram_message_logs')
    op.drop_table('telegram_message_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_message_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('input_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('output_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='telegram_message_logs_pkey')
    )
    op.create_index('ix_telegram_message_logs_id', 'telegram_message_logs', ['id'], unique=False)
    # ### end Alembic commands ###
