"""fixes

Revision ID: e435c4c8d3cc
Revises: cb89c566f9ba
Create Date: 2024-12-02 14:07:27.153942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e435c4c8d3cc'
down_revision: Union[str, None] = 'cb89c566f9ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app', 'inst_app_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('app_inst_app_id_key', 'app', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('app_inst_app_id_key', 'app', ['inst_app_id'])
    op.alter_column('app', 'inst_app_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
