"""add handle_code_url

Revision ID: f5e7b1931c8c
Revises: 4d534b963a91
Create Date: 2024-12-01 18:32:14.840461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5e7b1931c8c'
down_revision: Union[str, None] = '4d534b963a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('handle_code_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app', 'handle_code_url')
    # ### end Alembic commands ###
