"""whatsappuser

Revision ID: f97b07a57b20
Revises: 2d4b1e9fb85e
Create Date: 2024-12-17 11:28:25.021245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f97b07a57b20'
down_revision: Union[str, None] = '2d4b1e9fb85e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'instagram_verify_token', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instagram_verify_token', type_='unique')
    # ### end Alembic commands ###
